### ISSUE TITLE
Keep track of reliabilities and comments

### ISSUE THREAD

**Issue by ntejos** [jnburchett/joebvp#13]
As stated. We need a way to keep track of reliability and comments for each component. There are at least two approaches:

1. Create new mandatory columns in the output that are filled with the respective values when given in input, or filled with a default value when not given in the input.

2. Columns that are given in the input and are not mandatory, are still written in the output.

Option 2 is more general, option 1 more structured.

**Comment by jnburchett** [comment]
I think this has been addressed with the latest PR, right?

**Comment by ntejos** [comment]
Indeed.
