### ISSUE TITLE
Crashed out of blue during normal interactive use

### ISSUE THREAD

**Issue by tmtripp** [jnburchett/joebvp#3]
While inspecting quality of fits by clicking on various windows with the cursor, the code crashed out of the blue with the following error messages:

TypeError                                 Traceback (most recent call last)
/Users/toddtripp/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.pyc in mousePressEvent(self, event)
    257         if button is not None:
    258             FigureCanvasBase.button_press_event(self, x, y, button,
--> 259                                                 guiEvent=event)
    260         if DEBUG:
    261             print('button pressed:', event.button())

/Users/toddtripp/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in button_press_event(self, x, y, button, dblclick, guiEvent)
   1901         mouseevent = MouseEvent(s, self, x, y, button, self._key,
   1902                                 dblclick=dblclick, guiEvent=guiEvent)
-> 1903         self.callbacks.process(s, mouseevent)
   1904 
   1905     def button_release_event(self, x, y, button, guiEvent=None):

/Users/toddtripp/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, _args, *_kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(_args, *_kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/toddtripp/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in **call**(self, _args, *_kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(_args, *_kwargs)
    431 
    432     def **eq**(self, other):

/Users/toddtripp/python_code/joebvp/joebvp/VPmeasure.pyc in on_click(self, event)
    524     def on_click(self, event):
    525         self.lastclick=event.xdata
--> 526         self.sideplot(self.lastclick)
    527 
    528     def addmpl(self, fig):

/Users/toddtripp/python_code/joebvp/joebvp/VPmeasure.pyc in sideplot(self, cenwave, wavebuf)
    415         self.sideax.plot(self.wave, self.normsig, linestyle='steps-mid', color='red', lw=0.5)
    416         self.sideax.plot(self.wave, -self.normsig, linestyle='steps-mid', color='red', lw=0.5)
--> 417         self.sideax.set_xlim(cenwave-wavebuf,cenwave+wavebuf)
    418         self.sideax.set_ylim(cfg.ylim)
    419         self.changesidefig(self.sidefig)

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by jnburchett** [comment]
Implemented error catching to hopefully prevent this crash.  Please reopen issue if encountered again.
